name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: xguimiranda
      - name: Commit & Push
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git pull
          git add profile-3d-contrib
          git commit -m "update 3d contribution graph" || echo "No changes to commit"
          git push

